### ISSUE TITLE
Regular expressions in dax utilities

### ISSUE THREAD

**Issue by aplassard** [VUIIS/dax#102]
Would it be possible to incorporate regular expressions into the dax utilities like Xnatdownload? i.e. I want all assessors of the type "Heckers_*" instead of listing out all of the assessors? I can definitely implement this during the daxathon if there isn't a chance before then.

**Comment by byvernault** [comment]
Hi guys,

I am looking into regex and adding what Andrew was suggesting into XnatUtils and maybe into other files of dax where we are filtering the list of scans/assessors.

Do we want to integrate the full development of regular expressions or just simple things like what Andrew is suggesting: the use of '*'?

For example, in regular expressions, Heckers_* will give you all the assessors with the type: Heckers_ and a number of repetition of _ so:
Heckers_
Heckers__
Heckers___
Heckers____
etc...

What do you think? Want?

Cheers,

Ben

**Comment by aplassard** [comment]
First, thanks for looking at this.

I think just implementing wildcards, a la how bash handles them, gets us a lot of the way further into usefulness. Just my two cents, simple wildcards are a great start.

I do think the one case where full regular expressions are useful are projects where scan names get a little funky, i.e. T1w, t1w, T1-W, T1/w, etc. But flip-side not implementing full regular expressions would force people to spend a little more time looking at exactly what they want.

I think this is an important discussion about a feature that will get a lot of use so if more people weigh in that would be really beneficial.

**Comment by Raab70** [comment]
I agree with Andrew, I think we should start with wildcards because they're the most ubiquitous. 

Regex support would be good later maybe with a flag to enable or disable regex interpretation of inputs.

**Comment by aplassard** [comment]
Thats a good idea. It would be easy enough to have a flag like "--full-regex" which when active uses the regex as is whereas the standard mode is to convert the wildcard string to its regex equivalent, something like 

match_string = match_string.replace("*", ".*")

I'm not sure how replace implements regular expressions, so that may not even be close to the right command and it may need escaped to death, but you get the idea.

**Comment by Raab70** [comment]
it would probably just be:

match_string = match_string.replace("*",".*")

**Comment by aplassard** [comment]
TIL git comments don't like \*s

**Comment by Raab70** [comment]
[**Markdown** is still better than rst](https://guides.github.com/features/mastering-markdown/) @damonms

**Comment by byvernault** [comment]
Hey guys,

I have worked on the branch "regex" (https://github.com/VUIIS/dax/tree/regex) to add regex for the options --subj/--sess/-s/-a. You can specify for example:

Xnatdownload -p INNOVATE -s *b3000* --rs NIFTI -d data/testregex 

You can also use the --fullRegex options to use regex in it's full form. I am using the python package fnmatch to convert the string into regex expressions. 

Let me know what do you think about it. I can then add it to each tool and incorpore it in dax code as well.

Cheers,

Ben

**Comment by byvernault** [comment]
We pushed the regex branch quite some time ago into DAX. 

I am closing the issue. Feel free to reopen it if you have any more questions/comments.

Cheers,
Ben
