### ISSUE TITLE
results dir should os.path.expanduser

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#106]
right now ~/RESULTS_XNAT_SPIDER gets generated but on some OSs it doesn't like the ~ so we should os.path.expanduser like home

**Comment by byvernault** [comment]
I think we fix this issue:

`def get_results_dir(self):
        """Get the results_dir value from the cluster section.

        :return: String of the results_dir value, None if empty
        """
        resultsdir = self.get('cluster', 'results_dir')
        if resultsdir is None:
            resultsdir = '/tmp'
        if resultsdir.startswith('~'):
            return os.path.join(os.path.expanduser('~'), resultsdir[2:])
        else:
            return resultsdir`

I will close it but feel free to reopen it if it's not the case and I will look more into it.
