### ISSUE TITLE
anonymization

### ISSUE THREAD

**Issue by elijahrockers** [VUIIS/dax#115]
Not sure if this is the right place, but 

I have 75 subjects that have identifying info in a project. I can anonymize them via XNAT now that I have the project anonymization script, but to do so I have to rename each session (and then name it back) causing the project anonymization script to run.

Is there a solution that can anonymize all my scans at once?

**Comment by damonms** [comment]
Do you have access to the archive? You could run anonymization right on the archive, though you would need to regenerate the checksums to ensure data consistency.

**Comment by elijahrockers** [comment]
Yes, but I don't want to necessarily run the anonymization script on the entire archive, just the individual project... I suppose I _could_, but we have very many projects and subjects so it would probably take a very long time.

**Comment by damonms** [comment]
The archive is stored by project so it should be pretty straightforward to just run on the project that you want and avoid all others.

________________________________

**Comment by damonms** [comment]
I believe you can trigger the anon script through API as well

________________________________
From: Damon, Stephen M
Sent: Wednesday, August 24, 2016 8:57 AM
To: VUIIS/dax; VUIIS/dax
Cc: Comment
Subject: RE: [VUIIS/dax] anonymization (#115)

The archive is stored by project so it should be pretty straightforward to just run on the project that you want and avoid all others.

________________________________

**Comment by elijahrockers** [comment]
OK thanks, I will take a look.

**Comment by elijahrockers** [comment]
I didn't quite understand what I was talking about before, but I have had a lot more experience now. Yes, I have access to the archive... how would I run anonymization directly on the archive (and regenerate checksums)?

**Comment by elijahrockers** [comment]
OK I see now that I can use dcmodify... but what's the business with checksums? Aren't the checksums going to be different if I modify the tags?
