### ISSUE TITLE
is_cscan_good_type bug

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#129]
The regex isn't working appropriately. T1WMT is getting matched to T1 when it shouldn't resulting in Multi_Atlas running on MT data and not just T1 and MPRAGE data. I'll work on a fix. We need to update this one sooner rather than later...

**Comment by damonms** [comment]
So it looks like this was probably changed to handle regex in some of the CLI tools. Does everyone want a separate method that works the old way( basically cscan.info()['type'] in type_list) or a fix through the CLI tools?

**Comment by byvernault** [comment]
Hey Steve,

Could you send me the list of scantypes and the expression you gave?

Cheers,

**Comment by byvernault** [comment]
The code I added from the request is in the update_tools request.

I will try to check to see if I can find the issue since it didn't fix it.

**Comment by damonms** [comment]
What if we just have two methods. The old one which doesn't change functionality and the new one with _regex added on the end? That way we don't break backwards compatibility

**Comment by byvernault** [comment]
Sure, what about we add a no_regex argument for the spiders so it won't use it and do like before?
