### ISSUE TITLE
Xnatmirror broken

### ISSUE THREAD

**Issue by elijahrockers** [VUIIS/dax#139]
I am using Xnatmirror to migrate to a newer version of XNAT. However the current release of dax throws an error when I try to use it. (I actually tried dax 4 5 6 and 7)

I got around it by reverting to an earlier version and commenting out the block that calls XnatUtils.has_dax_datatypes. Also left SKIPPING_PROC_DATA = True uncommented. 

So the files appear to be copying now, but I just wanted to let y'all know it doesn't work "out of the box". The more recent versions gave me some kind of an error with Tkinter, and another version also threw errors that looked like it was assuming I was on a cluster (it was looking for some head node configuration or something)

Also.... the Xnatmirror source code under the "current" github master does not even make it to that code block because there is something wrong with the argument parser. Doing a pip --upgrade gives us a version where that works but iirc throws the cluster errors

**Comment by byvernault** [comment]
Hi Elija,

Thanks for the message.

I will try to look at it with Brian. 

The Tkinter issue is from matplotlib that uses in the newest version Ttk and I have seen a lot of python where there is an issue with it. You need to have a python installed with ttk. It should be by default but I have seen some python without. (see http://stackoverflow.com/questions/3080918/why-cant-i-use-ttk-in-python , http://stackoverflow.com/questions/26702119/installing-tkinter-on-ubuntu-14-04 )

Cheers,

Ben

**Comment by byvernault** [comment]
If your XNAT instance doesn't have the dax datatypes installed, it should print a warning and ask you if you want to skip them. Do you see that message? Did you answer yes?

Which error did you get?

**Comment by elijahrockers** [comment]
No. Didn't see that error because it could n't find
XnatUtils.has_dax_datatypes in the first place. That's why I ended up just
commenting it out.

**Comment by byvernault** [comment]
The function has_dax_datatypes is present in XnatUtils. You might have a issue with dax package (different packages installed). 

You might want to desinstall all of them and reinstall one.

**Comment by elijahrockers** [comment]
If that is "pip uninstall dax", I did that several times when trying
different versions. Dax did not exist on my system before. ( just switched
OS )

**Comment by elijahrockers** [comment]
Encountered another separate issue, but not really related with dax... but just hoping you might be able to give me some insight...

The source XNAT has a project with incorrect demographic info. Handedness is R/L isntead of right/left ... this gives an error (not sure how this happened in the first place

    The content of element 'xnat:demographicData' is not complete. '{"http://nrg.wustl.edu/xnat":handedness}' 'R' Must Match Pre-Defined Values...(left,right,ambidextrous,unknown)

There are too many subjects to do by hand, what's the best approach here?

**Comment by elijahrockers** [comment]
Nevermind we just used a for loop in pyxnat to fix them.

**Comment by byvernault** [comment]
I am closing this issue. Feel free to open it again if you want to add something.

Cheers,
