### ISSUE TITLE
is_bad_qa bug?

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#140]
get_good_cassr returns assessors with NEED_INPUTS. I don't think this should be the case? Thoughts?

**Comment by bud42** [comment]
Yeah, looks like the NEED_INPUTS used to get filtered out because the qcstatus was always Job Pending. Then we started putting more specifics about the inputs that were missing into the qcstatus.

**Comment by byvernault** [comment]
It looks like this is a bug. We should add NEED_INPUTS to the list of qc status that returns 0 since we don't want to do anything until we got inputs.

Thoughts? Should we add it to master directly? 

Since it isn't a BAD_QA_STATUS, it will return 1.
