### ISSUE TITLE
Xnatdownload feature request

### ISSUE THREAD

**Issue by bud42** [VUIIS/dax#141]
It would nice to be able to filter the assessors downloaded based on scan type. Maybe there's a way to accomplish this already? Someone just asked me if it was possible and I didn't have an answer.

**Comment by byvernault** [comment]
Do you mean something like:

Xnatdownload -p PID -d FOLDER -s T1 --proc 

And this will download the T1 and all scan assessors that ran on this T1.
For session assessor, it's more difficult.
