### ISSUE TITLE
Double Assessors with sharing sessions

### ISSUE THREAD

**Issue by byvernault** [VUIIS/dax#148]
Hi guys,

I realised today something odd but it makes sense why we have this. If a session that has existing assessors is shared to a new project where you run the same spiders, it will creates a new assessors (with the new project name) on the same session.

Example:
If you have a project called TEST where you run fMRIQA_v1 for example via DAX, you will for the session s01_1 under the subject s01: TEST-x-s01-x-s01_1-x-3-x-fMRIQA_v1. Normal.
Now, if you create a new project TEST2 and you share the session s01_1 to this project and run fMRIQA_v1 via DAX as well, you will see a new assessor in your session called:
TEST2-x-s01-x-s01_1-x-3-x-fMRIQA_v1
It makes sense as well.

But since XNAT when sharing a session, just use the same location between project, it means that you will see in both projects all those assessors.

I am trying to think if we could do something to fix this  behavior. Should we check if either project_id or project_id_shared assessors existed when looking at should_run()?

Cheers,

**Comment by bud42** [comment]
fixed by c07f3f8958703555a05e3eae90d27a84556d8941
