### ISSUE TITLE
When XNAT is not available jobs are marked as failed

### ISSUE THREAD

**Issue by aplassard** [VUIIS/dax#16]
SpiderProcessHandler attempts to access XNAT. If it cannot the class throws an exception and the job gets marked as failed in its output status file and thus this is the status when the data get uploaded to xnat even though in all likelihood the process did not fail.

**Comment by byvernault** [comment]
Hey Andrew,

I see what you are talking about. If it doesn't access XNAT, it will throw an error instead of just keep going and let dax_upload set the status later on. 

I will work on a fix for that.

Best,

Ben

**Comment by bud42** [comment]
Fixed by Ben in PR #19
