### ISSUE TITLE
The substring 'python' in a settings yaml causes it to be parsed as a python file in dax test

### ISSUE THREAD

**Issue by atbenmurray** [VUIIS/dax#171]
Dax has python files without a .py ending, and these get read and parsed by code that also loads yaml settings files. The ordering of the logic is as follows:
1. check if file as .py ending or has python substring (from the python shebang)
2. else check if the file is a .yaml file
The 'or has python substring' check means that any .yaml settings file with 'python' anywhere in the file will be treated as a python file.

The simple fix is to check for the .yaml ending first.
Note, this only affects dax test.

**Comment by bud42** [comment]
@atbenmurray can you point me to this in the code? I don't see it.

**Comment by atbenmurray** [comment]
Apologies for the late response. Looks like I didn't move across to vuiis from my fork. Will do first thing tomorrow.

**Comment by baxpr** [comment]
This is old - I hope now fixed? Please reopen if not.
