### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by bud42** [VUIIS/dax#172]
Hi Folks,

Let's make a new release and push it to PyPi. If you have any changes you would like included, please submit a PR to merge with the release candidate branch [v0.8.rc1](https://github.com/VUIIS/dax/tree/v0.8.rc1)
When everyone is happy with the branch, I will create a release. 

Thanks!
-Brian

**Comment by bud42** [comment]
Anyone? 
@justinblaber @KarthikMasi can you confirm that this branch is in sync with what is running on the shared accounts at Vanderbilt?

**Comment by vuiiscci** [comment]
Its not. I just sync'd what was running on masispider to the "accre" branch. We can try installing "v0.8.rc1" on masispider and see if it works. I have a feeling things will break though.

**Comment by bud42** [comment]
My changes have been merged. New version will be released by the end of this week and pushed to PyPi.

**Comment by bud42** [comment]
0.8.0 release created and pushed to PyPI.
