### ISSUE TITLE
Local flagging PR #165 'broke' dax upload

### ISSUE THREAD

**Issue by atbenmurray** [VUIIS/dax#175]
Hi folks,
As part of integration testing the changes for assessors of assessors #157, I notice that dax upload is defunct. Specifically, it calls dax_tools_utils.upload_tasks, which was gutted as part of the changes made for #165. I understand that file wrapping is performed in this function, and the lock file mechanism has been changed, but surely that doesn't break the entire code path? All our cron jobs for upload are written using dax upload and the docs refer to it, so it really ought to still be functional.
Does anyone know of any showstoppers that mean this code had to be removed in its entirety?
Thanks,
   Ben

**Comment by justinblaber** [comment]
We agreed (at least at the CCI) that flock should be used in the crontab (i.e. file locking is performed outside of dax upload). We have our crontab set up like:

*/5 * * * * ( flock -n ~/.dax_upload.lock -c ". ~/.bashrc && dax upload -e masi-admin@list.vanderbilt.edu --logfile ~/Xnat_management/DAXLogs/Upload_log/dax_upload_$(date +\%Y\%m\%d_\%H:\%M:\%S\%z).log" ) > /dev/null 2>&1

So dax upload is still functional if you set up your crontab this way. It shouldn't be too much to change this. 

If you really think file locking should be done within dax upload, then we can use the python flock wrapper library (fcntl) within dax. But basically we needed to do away with the file locking that was implemented because it wasn't done correctly (it was just hacked together and we would repeatedly have stale lock files or duplicate dax uploads running).

**Comment by atbenmurray** [comment]
Hi Justin,
It's more that dax upload functionality 'went away' in its entirety, but the docs still mention it.
As I understand it from flock documentation, the idea is that the cron job should be wrapped the way you specified, and then dax upload command can be reinstated minus the lock file code. That would be nice, because at the moment 'dax upload' is non functional and it breaks symmetry to have all the other commands callable in this way except upload.
What do you think?
Ben

**Comment by justinblaber** [comment]
Hmm @KarthikMasi should have just removed the file locking code and nothing else. Can you double check Karthik?

**Comment by KarthikMasi** [comment]
Yeah. I only removed the file locking code. We had it checked on multiple instances too before pushing it to the repository.

**Comment by mmodat** [comment]
Hi,

This is the current version of master in https://github.com/VUIIS/dax/blob/master/dax/dax_tools_utils.py#L481

```python
def upload_tasks(logfile, debug, upload_settings=None,
                 host=None, username=None, password=None,
                 projects=None, suffix=None, emailaddress=None):
    """
    Upload tasks from the queue folder.
    :param logfile: Full file of the file used to log to
    :param debug: Should debug mode be used
    :param upload_settings: settings file (csv, py, json) to define
                            xnat host/project relationship.
    :param host: XNAT host
    :param username: XNAT username
    :param password: XNAT password
    :param suffix: suffix for flagfile
    :param emailaddress: email address for warnings
    :param projects: Project(s) to upload
    """
    bin.set_logger(logfile, debug)

    # Check if folders exist
    check_folders()
    ##flagfile = "%s%s.txt" % (FLAGFILE_TEMPLATE, suffix)

    # Load the settings for upload
    #upload_settings = load_upload_settings(upload_settings, host, username,
    #                                       password, projects)
    #print_upload_settings(upload_settings)
    # create the flag file showing that the spider is running
    ##if is_dax_upload_running(flagfile):
    ##    pass
    ##else:
    ##    try:
    #upload_results(upload_settings, emailaddress)
    ##    finally:
            # remove flagfile
##        os.remove(flagfile)
```

**Comment by justinblaber** [comment]
@KarthikMasi  Can you look at:

https://github.com/VUIIS/dax/blob/4c123fe74b02e1bec45612a4001dda4f28824de6/dax/dax_tools_utils.py

Line 514 is commented out. I don't think it should be? The way it looks, upload_tasks appears to be entirely commented out.

**Comment by KarthikMasi** [comment]
Oh yes. We rectified this previously. And I should have had the branches mixed up when I pushed them back. I will just push the code to master again.

**Comment by atbenmurray** [comment]
Karthik, can you just point me at the branch in question? I have a hell of a PR coming up and I've reinstated that code in the asr_of_asr branch on my fork, plus the tweaks required for the changes I've been making. The fact that it went unnoticed for several months means it probably only would have broken stuff for us anyway!

**Comment by KarthikMasi** [comment]
The changes were made to branch "filelocking". I have pushed to master with the recent changes.

**Comment by bud42** [comment]
The default behavior has been reverted to use the lock file. To disable locking for dax upload use the flag "--nolock".
