### ISSUE TITLE
Feature request: patch up old assessors with 'inputs' field when inputs can be unambiguously determined

### ISSUE THREAD

**Issue by atbenmurray** [VUIIS/dax#189]
Where an assessor's inputs can be determined by unambiguously by inferring the contents of a session or sessions, it should be possible to retrospectively set those inputs on the inputs field of the assessor in question. This should only happen when the user explicitly intends it, rather than being implicitly performed as part of a standard DAX command such as 'build'.

**Comment by atbenmurray** [comment]
Just FYI, we needed it for a project here and so I put together a first-pass of the functionality, currently on the branch 'pie_bsi_test'. I'll rebase to a branch called '189_patch_assessor'.

**Comment by baxpr** [comment]
Looks abandoned. But if I'm wrong please feel free to reopen or make the PR.
