### ISSUE TITLE
SpiderProcessHandler: add explicit/clear error message if no PDF found

### ISSUE THREAD

**Issue by atbenmurray** [VUIIS/dax#193]
While PDFs are convenient and in general it is good practice to provide a pdf with the output of an assessor, it is overly harsh for the assessor to be marked as failed, especially as no warning specifying that a pdf must be provided in the PDF resource folder is given.
I suggest either:
1. We remove this requirement, or, if that is unacceptable
2. We make it clear to the user that this is why the assessor is marked JOB_FAILED

**Comment by BennettLandman** [comment]
We need this requirement as it represents a fundamental design requirement.

I'm fully supportive of more detailed error messages.

-----Original Message-----

**Comment by atbenmurray** [comment]
Fair enough. 2 it is then

**Comment by baxpr** [comment]
Currently a missing PDF should be evident from the OUTLOG if the job has failed. But, maybe this should be made clearer or indicated in dax logs as well?

**Comment by baxpr** [comment]
PDF handling will be a little different in next release
