### ISSUE TITLE
Logger is print to stderror for info

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#20]
Xnatcheck -p ABIDE --filters proctype=fMRI_Connectivity_PreProcess_Scan_v1 1> 1.txt 2> 2.txt

**Comment by byvernault** [comment]
I fixed/tested it in the branch spiders_class that will be merged as soon as I am done with it.

Thanks Steve.

Best,

Ben

**Comment by damonms** [comment]
Awesome, thanks!
