### ISSUE TITLE
dax readthedocs owners

### ISSUE THREAD

**Issue by bud42** [VUIIS/dax#202]
Could someone add me to the owners for DAX on readthedocs? 
@byvernault @damonms @yuankaihuo  ?

Thanks!

**Comment by byvernault** [comment]
Hello Brian,

How are you doing?

I don't think I still have any rights on VUIIS.
Steve was the one taking care of the readthedocs.
He might know about it.

Kind regards,

Benjamin

**Comment by bud42** [comment]
resolved. thanks Bennett!
