### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by bud42** [VUIIS/dax#206]
FYI, I'm working on a v1.0 release on the rc1 branch. Here's what I'm thinking:
-not backwards compatible
-require yaml processor (drop support of old style processor/spider)
-limit dependencies to pyxnat and pyyaml
-require Python3
-remove extraneous code
-automate unit and integration testing
-full documentation of yaml processor with section-by-section guide
-more optimization of dax build

Feedback appreciated!

**Comment by bud42** [comment]
Just a quick update on this effort. I am now actively running the rc1 branch. 
- [x] not backwards compatible
- [x] require yaml processor (drop support of old style processor/spider)
- [x] limit dependencies to pyxnat and pyyaml
- [x] require Python3
- [x] remove extraneous code
- [x] full documentation of yaml processor with section-by-section guide
- [x] more optimization of dax build
- [  ] automate unit and integration testing

**Comment by bud42** [comment]
- [X] all XNAT API calls are wrapped with a timeout that will email the admin on first timeout and will then retry the specified number of times with a specified wait time in between retries.

**Comment by damonms** [comment]
@bud42, what depth of integration testing is the group after? I have some free time (don't have a grid to test on) but might be interested in a sandbox env, and or booting up a virtual grid
