### ISSUE TITLE
New style assessors break XnatSwitchProcessStatus

### ISSUE THREAD

**Issue by atbenmurray** [VUIIS/dax#207]
New style assessor labels break XnatSwitchProcessStatus. The break is caused by calls to XnatUtils.select_assessor, which works off the label being formatted in the old proj-x-subj-x-sess-x-(scan-x-)name format. The sensible fix is to no rely on names being formatted this way, but I suspect that there are paths where that is all you have, so a fix needs to account for that scenaro too

**Comment by baxpr** [comment]
I think this is fixed now - @bud42 can you confirm?

**Comment by baxpr** [comment]
No updates in a long time and I think it's no longer a problem - I'm expiring this ticket, but please bring it back if it's still an issue
