### ISSUE TITLE
The HEAD Branch does not have a working version of requests

### ISSUE THREAD

**Issue by aplassard** [VUIIS/dax#22]
I recently installed dax from the HEAD and it does not look like the version of requests works. I get the error message: pkg_resources.UnknownExtra: requests 2.2.1 has no such extra feature 'security'

**Comment by damonms** [comment]
Confirmed on build server: http://masijenkins.vuse.vanderbilt.edu:8080/job/Build%20DAX/6/consoleText

**Comment by damonms** [comment]
Looks like the default install 2.2.1 is assumed to be good, even though pyxnat requires the security extra package (which obviously wasn't part of 2.2.1). I ran this on the build server:
sudo pip install requests --upgrade
sudo pip install requests[security]

and it fixed the issue.
http://masijenkins.vuse.vanderbilt.edu:8080/job/Build%20DAX/lastSuccessfulBuild/console
