### ISSUE TITLE
Script to check for long-open flag files

### ISSUE THREAD

**Issue by aplassard** [VUIIS/dax#23]
I believe Ben was working on a script that checked the flag files for ones that were active for a long period of time. Was this ever completed? It would be nice for situations when everything stops like this weekend.

**Comment by damonms** [comment]
find /scratch/vuiiscci/Spider_Upload_Dir/FlagFiles/* -mtime +2 -delete 

This should handle it. Really we don't want anything running over a day but I could see the possibility when someone wants to generated several thousand new assessors which would take a while so let's give it a day of overhead.
