### ISSUE TITLE
Xnatdownload not finding data shared from another project

### ISSUE THREAD

**Issue by davecash75** [VUIIS/dax#233]
Hi there-
We use Xnatdownload a lot for bulk downloading of data to projects. IN one such project, we have a "master" project where we prepare data for public release. Then, we share all of that data into  various "data freeze" projects, where users who have had research proposals approved can have access to the data at the time their proposal was approved. What we have noticed is that when a user tries to download data from one of these datafreeze projects for which they have access, Xnatdownload states that there is no data that matches the query. We looked into this more and once we gave them access to the master project, then Xnatdownload using the same command as above (specifying the datafreeze project with the -p option, not the master) returned the expected data for download.
WE noticed this in versions 0.7 0.9 and 0.11. Is this something that has been subsequently fixed or expected behavior?
Many thanks
David Cash

**Comment by bud42** [comment]
I was not able to reproduce this in v1.0.0. Trying v0.11 now.

**Comment by bud42** [comment]
v0.11.5 worked too. @davecash75 what version of XNAT are you running? We are on 1.7.5.

**Comment by davecash75** [comment]
Unfortunately an old one. At the moment the server in question is 1.6.4

**Comment by baxpr** [comment]
@davecash75 any news on this problem with sharing in XNAT 1.6.4? I don't think we're going to be able to debug issues with the older XNAT releases on our end.

**Comment by davecash75** [comment]
HI there- that's fine. We have a plan to migrate this to a new version of XNAT, so I think that is the best way forward to resolving it.

**Comment by baxpr** [comment]
Ok, thanks. Good luck!
