### ISSUE TITLE
get_good_cassr is broken

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#24]
def is_cassessor_usable(cassr):
    """ return 0 if assessor not ready or doesn't exist
        return -1 if assessor failed
        return 1 if ok
    """
    assr_info = cassr.info()
    return is_bad_qa(assr_info['qcstatus'])

Returns -1 if the assessor status is "bad". In the function get_good_cassr

def get_good_cassr(csess, proctypes):
    """ return cassr list from a csess if there is a good assessor """
    cassr_list = list()
    for cassr in csess.assessors():
        if is_cassessor_good_type(cassr, proctypes) and is_cassessor_usable(cassr):
            cassr_list.append(cassr)
    return cassr_list

-1 returns True in an if statement and thus returns 'bad' and 'fail' assessors as "good" ones in cassr_list

**Comment by byvernault** [comment]
Good catch Steve. I didn't realise that.

We can fix it by adding two lines:

usabel = is_cassessor_usable(cassr)
if is_cassessor_good_type(cassr, proctypes) and usable == 1:

Do you want me to do the changes?
It will need to be replaced as well in the method get_good_assr(session_obj,
proctypes.

Cheers,

BenJ

**Comment by damonms** [comment]
Hey Ben,

Yes, that sounds great!

Steve

**Comment by byvernault** [comment]
The changes have been applied. It should be good now. I will let you confirm and close your issue.
Sorry for that,

Cheers,
Ben

**Comment by damonms** [comment]
Confirmed working -- I'll close.

Thanks Ben!
