### ISSUE TITLE
NEED_INPUTS status only logged to STDOUT

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#26]
Not necessarily an issue, but kind of. I get a lot of requests why the status is NEED_INPUTS. What are everyone's thoughts on setting this in the QC status (like we do for NO_DATA) rather than grepping through the build log? This should alleviate unnecessary emails (I think; assuming we set appropriate and intelligent debug info like "No DTI scan").

**Comment by bud42** [comment]
This is a great idea. Let's do it.

**Comment by damonms** [comment]
I'll include this in my subject_spiders branch

**Comment by cfo3vu** [comment]
Thanks Steve,

I think this is a great idea as well!

Best,
Charles


On Nov 19, 2015, at 1:38 PM, damonms <notifications@github.com<mailto:notifications@github.com>> wrote:


I'll include this in my subject_spiders branch

**Comment by damonms** [comment]
I'm closing this issue as we have fixed this.
