### ISSUE TITLE
Xnatinfo (list_project_scans) doesn't work with HD_Sessions

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#27]
For Xnatinfo, and more generally XnatUtils methods, all returns are 0 for list_project_* methods (scans, subjects, assessors etc). This recently was noticed with the addition of NIRS data as the "HD_Session" type in XNAT.

**Comment by byvernault** [comment]
I will look at it tomorrow if I have some time.

Thanks Steve.
Cheers,

Ben

**Comment by damonms** [comment]
It's not a huge issue. I just came across it today testing a new spider. I can tackle it since I have several test projects. Also no one is asking for it yet so definitely not at the top of the list.



Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by byvernault** [comment]
I created a HD sessions for one of my test project and I use XnatUtils.list_sessions and list_scans, I was able to grab the HD session as well as the scans. Let me check Xnatinfo and list_projects_*.

**Comment by byvernault** [comment]
I checked as well Xnatinfo and I can see my two scan in the list of types. I don't have any assessor on it so I can't tell about it.

I use as well list_projects_scans and I have my scan from my HD sessions that appears. Again, I don't have any assessor so I haven't tried the list_project_assessors.

**Comment by damonms** [comment]
Works on the exact same project. Not sure what happened. Maybe a gamma ray hit our vm? Closing as not a bug.
