### ISSUE TITLE
NEED_INPUTS, JOB_RUNNING status is ambiguous

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#277]
NEED_INPUTS may mean what it says, or it may mean that all inputs are present and the job just hasn't launched.

JOB_RUNNING may mean what it says, or it may mean the job has finished and is waiting in the upload queue.

I'm not sure how practical it would be to add statuses like WAITING_TO_LAUNCH and WAITING_TO_UPLOAD, but these would substantially reduce user confusion.

**Comment by bud42** [comment]
The status will be JOB_RUNNING when dax writes the batch script until it's being uploaded. The status does not update when the job actually launches on the cluster. NEED_INPUTS does mean that all inputs are not present (or dax hasn't checked for inputs yet).

**Comment by baxpr** [comment]
Uploads are not getting bogged down lately anyway, so a separate upload indicator wouldn't be so helpful anyway. I'll close this, it doesn't seem important/helpful enough to spend time on.
