### ISSUE TITLE
Get all settings from REDCap and organize remaining scripts/templates 

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#283]
Eventually should we have all settings in the REDCap Instances control panel, instead of .dax_settings.ini ?

A likely exception would be the XNAT credentials, currently in ~/.netrc which seems good to me.

There is also /data/mcr/slurm_commands/sbatch_retry - not sure if it's still used, but if so, it might be good to move it to dax_templates repo or somewhere like that.

**Comment by bud42** [comment]
fixed in dax v2.0.0
