### ISSUE TITLE
Sessions getting skipped when they should be built

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#289]
It seems like dax skips a session if there hasn't been a change on XNAT since the last build, right?

This results in skipping sessions inappropriately when there has been a change in REDCap settings. Two recent examples:

- Changed processor filename in REDCap and switched assessor status from "Incomplete" to "Complete". I guess sessions were skipped because a same-named assessor had previously been built? Although the previously built assessors had been deleted. http://xnatbug.vandyxnat.org/bugzilla/show_bug.cgi?id=1542#c42

- Added a new scan type in the list in REDCap. http://xnatbug.vandyxnat.org/bugzilla/show_bug.cgi?id=1534#c6

- Turn on a new assessor or module in REDCap.

- Add a new instrument/assessor in REDCap.

- Change assessor notes field in XNAT, e.g. force re-upload for the REDCap sync module.

**Comment by duettwe** [comment]
To go along with the first bullet there, it looks like any change to an assessor makes it not get picked up (arguments or filename).

- Module_redcap_sync_yaml turned on

**Comment by bud42** [comment]
fixed in dax 2.0.0
