### ISSUE TITLE
Spiders latest Version

### ISSUE THREAD

**Issue by aissamr38** [VUIIS/dax#305]
Hello all the DAX team,

Firstly Thank you for this great project.

We are in the process of setting up DAX on our system. After some progress in this project, and also after an inspection of your documentation, we noticed that the part concerning the creation of **Spiders** and its examples [https://github.com/VUIIS/dax/blob/master/test/pipelines/Proc_A/v1.0.0/Proc_A_v1_0_0.py](url) are not referenced (does not exist in the latest version doc https://dax.readthedocs.io/en/latest/).
Could you please tell us if we will have to use the old versions for this case?

Regards

**Comment by baxpr** [comment]
Hi! Thanks for your interest. That particular link is to some test code that I believe was never quite finished, and at any rate hasn't been looked at in a few years.

For info on creating spiders in general, maybe start here: https://dax.readthedocs.io/en/latest/processors.html
https://dax.readthedocs.io/en/latest/dax_manager.html

I'm not sure I answered your question though - let us know.

**Comment by aissamr38** [comment]
Hi!
Thank you for your reply,

Exactly this link refers to the creation of the **Spiders**. But the content is empty. you can verify that.
you can also check this link [Class Spider](https://dax.readthedocs.io/en/master/dax.html?highlight=Spider#dax-spiders-spider-class)

**Comment by baxpr** [comment]
@aissamr38 I'm not sure we have a step by step for making spiders. But here is an example of building a singularity container:
https://github.com/baxpr/freesurfer-singularity

And the yaml that DAX uses to [run it via REDCap](https://dax.readthedocs.io/en/latest/dax_manager.html#how-to-add-a-process-in-dax-1):
https://github.com/VUIIS/dax_yaml_processor_examples/blob/master/freesurfer_dev_v2.0.0.yaml
