### ISSUE TITLE
Is there an opposite of AssessorHandler?

### ISSUE THREAD

**Issue by aplassard** [VUIIS/dax#31]
I really like the functionality of the AssessorHandler. I feel like it makes my code significantly more readable. I was wondering if we have the inverse function in the works? I.e. I have a project, subjects, session, and scan, make me the string or the same class basically.

**Comment by byvernault** [comment]
Hi Andrew,

There is a get_assessors functions in XnatUtils but it will return the assessor object and not the string.
I will work tomorrow on adding something like that to the AssessorHandler to init it with project subjects session and scan or just a function that returns an AssessorHandler object.

Good idea.

Cheers,

Ben

**Comment by byvernault** [comment]
Hi Andrew,

Are you looking just for a function like:

def generate_assessor_handler(project, subject, session, proctype, scan=None):
    """
    Generate an assessorHandler object corresponding to the labels in the parameters

    :param project: project label on XNAT
    :param subject: subject label on XNAT
    :param session: session label on XNAT
    :param proctype: proctype for the assessor
    :param scan: scan label on XNAT if apply
    :return assessorHandler: assessor handler object
    """
    if scan:
        assessor_label = '-x-'.join([project, subject, session, scan, proctype])
    else:
        assessor_label = '-x-'.join([project, subject, session, proctype])
    return AssessorHandler(assessor_label)

Cheers,

Ben

**Comment by aplassard** [comment]
I think that would work.
Thanks!

**Comment by damonms** [comment]
Cool, I like it!
________________________________

**Comment by byvernault** [comment]
I am closing this issue. The functions is in the push request from Steve about sphinx and documentation. It should be added soon.

Cheers,
Ben
