### ISSUE TITLE
command : dax test --file  (Dax Version 2.0.0)

### ISSUE THREAD

**Issue by aissamr38** [VUIIS/dax#312]
Hello Dax team,
I just moved to the new version of dax v2.0.0
I'm asking  how I can make a **test file** ( **dax test --file** ). I have noticed that the **dax test** command doesn't exist in dax v2.0.0.

I also ask if Would there be a new version of the documentation for new updates of dax ?

Sincerely

**Comment by baxpr** [comment]
Documentation is in the repo, and also shows up here: https://dax.readthedocs.io/en/latest/ Feedback or fixes always welcome if something is out of date.

No recent action on this issue so closing.
