### ISSUE TITLE
Docs - .netrc file format

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#317]
~/.netrc has to look like this now:
```
machine xnat.vanderbilt.edu
login username
password password123
```

not like this:
```
machine https://xnat.vanderbilt.edu/xnat
login username
password password123
```

Is this clear in the docs? Especially the setup docs?

**Comment by baxpr** [comment]
e.g. http://xnatbug.vandyxnat.org/bugzilla/show_bug.cgi?id=2011

**Comment by duettwe** [comment]
Updated https://github.com/VUIIS/dax/blob/main/docs/installing_dax_in_a_virtual_environment.rst under the 'make sure your netrc looks like this' section with:

_Make sure that the xnat_host is formatted similarly to 'xnat.website.com' NOT 'https://xnat.website.com/xnat'. The full url is not required and WILL NOT WORK properly._

**Comment by bud42** [comment]
<img width="748" alt="screenshot" src="https://user-images.githubusercontent.com/2931954/112910330-26dc6d00-90c1-11eb-88f9-94f57a04cda2.png">

**Comment by bud42** [comment]
I installed from the main branch and did a fresh set up. See screenshot. New release is forthcoming.
