### ISSUE TITLE
XnatUtils is a mess

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#32]
We need to clean this piece up. Errors need to be actual errors. For example, just because a download directory doesn't exist, doesn't mean we should print an error. If that really needs to be an error, it should error. However, I think we could just make the directory. This came about as I'm updating all the docstrings for Sphix. 

Thoughts?

**Comment by byvernault** [comment]
I agree.

I don't have time until February to do this but we should definitely do
that.

Cheers,

Ben

**Comment by damonms** [comment]
No problem. I'm happy to work on it as well. I just didn't want to forget :)

**Comment by damonms** [comment]
Circling back here. I have all the debugging on pyxnat turned on. This has been pretty helpful in seeing repeated requests. For example, some of the download utils make a triple check before downloading. Thoughts on XnatUtils2? That way we don't have to go an update every spider, every processor, every tool etc.

**Comment by damonms** [comment]
Here's what I've started so far. Any comments before I get even deeper would be great 

https://github.com/VUIIS/dax/tree/xnatutils2

**Comment by damonms** [comment]
Scheudled for DAX Hackathon
