### ISSUE TITLE
base Dax Docker image install broken

### ISSUE THREAD

**Issue by elijahrockers** [VUIIS/dax#322]
base Dax docker image doesn't build correctly. Error is on the "RUN pip install dax" command. Here's relevant part of the error:

    pip install dax
    
    Downloading/unpacking dax
    Getting page https://pypi.python.org/simple/dax/
    Could not fetch URL https://pypi.python.org/simple/dax/: 403 Client Error: [[[!!! BREAKING CHANGE !!!]]] Support for clients that 
    do not support Server Name Indication is temporarily disabled and will be permanently deprecated soon. See 
    https://status.python.org/incidents/hzmjhqsdjqgb and https://github.com/pypa/pypi-support/issues/978 [[[!!! END BREAKING 
    CHANGE !!!]]]``

This seems to be a recent break related to the old version of Python ( < 2.7.9, which is EOL) and thus, pip.

**Comment by baxpr** [comment]
dax has been on python 3 for a while now. Where are you getting the dockerfile? You may need something like this (for ubuntu):
```
apt install -y python3 python3-pip python-is-python3
pip3 install dax
```
But that's from something else I've been working on - it's not tested for dax.

**Comment by elijahrockers** [comment]
I copied and pasted the Dockerfile from the readme (https://github.com/VUIIS/dax)

I was worried that dax would be using deprecated python 2.7 functions, but if it's updated for python 3 then maybe it's just as simple as installing python3 using your apt commands? The provided dockerfile uses Ubuntu 14 as a base image, if that's relevant...

By the way ... My goal is to use Xnatmirror to migrate data from one instance to another, which I have done in the past ... if you know of a more appropriate tool I'm all ears .... we are upgrading production XNAT from 1.6.5 to 1.8.1 and exploring options (migrate data to a new instance, vs. upgrade in place). Unfortunately Xnatmirror omits provenance data (rightly so, I understand) but I should explore the option anyway, just incase upgrading in place proves to be too fraught with errors...

**Comment by baxpr** [comment]
Oh, got it. That is pretty out of date - dax is on v2.1.0 now, and fully python 3.

Xnatmirror has not been updated or tested in a while (and see issue 287) so I'm not sure what your experience will be. Maybe @bud42 can chime in about the 1.8.1 upgrade.

**Comment by elijahrockers** [comment]
OK... maybe i can take a stab at creating a docker image for dax 2.1.0 then, if there's not one already.. 

I did see issue 287 but not sure I understand... sounds like assessors are copied for you, but not for OP? Either way I can maybe work on Xnatmirror also if it needs it.

**Comment by elijahrockers** [comment]
FYI it seems to be working with the python 3 packages you listed. 

That said, i ended up just downloading the source code and using Xnatmirror directly since I wasn't sure how to invoke it from dax .... I was able to copy a project with MRI from the 1.6.5 instance over to 1.8.1. Will be testing with Freesurfer data and some other assessors also to see if I can get that working ...

**Comment by baxpr** [comment]
Thanks for the update! Sounds resolved so I will close.
