### ISSUE TITLE
BOND dependency in v2.3.0

### ISSUE THREAD

**Issue by baxpr** [VUIIS/dax#336]
Missing dependency affecting Xnatdownload, http://xnatbug.vandyxnat.org/bugzilla/show_bug.cgi?id=2295

**Comment by praitayini** [comment]
@baxpr @lawlessrd @bud42 
comment from this pull request https://github.com/VUIIS/dax/pull/332
"The only requirement is pip install git+https://github.com/PennLINC/BOnD.git@v0.1.0"
I think this should help

**Comment by baxpr** [comment]
This is no longer called BOnD, but CuBIDS

**Comment by baxpr** [comment]
Was resolved at some point
