### ISSUE TITLE
Surround dax_build with a high level try catch?

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#36]
dax_build is the culprit here with lots of unhelpful database errors causing stuff to die consistently. Are there any objections to surround this process in a try/catch to catch all of pyxnat.core.errors?

**Comment by byvernault** [comment]
No problem, I like the idea.

Cheers,

Ben

**Comment by damonms** [comment]
I'm wrapping a fair amount of this into https://github.com/VUIIS/dax/tree/xnatutils2

Though, it's probably still necessary in other places. I'm closing this until I have a better on the depth that it will be in xnatutils2
