### ISSUE TITLE
fs:fsData optional and check datatypes installed

### ISSUE THREAD

**Issue by byvernault** [VUIIS/dax#37]
Hi guys,

I think we should probably have an option fs_datatype_on in dax_settings. Some other universities might want to just use proc:genProcData and not fs:fsData. 

Also, I am adding some lines of code to check that the datatypes are installed on Xnat before DAX do anything. It will raise an error. For listing assessors, it will just return an empty list and print a warning to the terminal. 

I am opening this issue just to remember to do that.
It's going to be in my branch on new options for Xnat tools.

Cheers,

Ben

**Comment by damonms** [comment]
I'll need to integrate this into what I'm working on in the refactor_dax_settings branch. What if we make it a bit more generic and have an xsitype_include variable? It could just be a list of xsitypes that are expected on XNAT. 

I agree it would be good to check that they exist before anything happens. Glad we found out we can do that with the Inspector class

Steve

**Comment by damonms** [comment]
I think this is done now right?

**Comment by byvernault** [comment]
Yes we can close this issue.
