### ISSUE TITLE
.netrc file with XNAT that has login, user and password

### ISSUE THREAD

**Issue by weberam2** [VUIIS/dax#409]
Hi
I am trying to login to my XNAT with dax but am having issues
My xnat is: https://3tfmri-xnat.bcchr.ca
If you go there with a browser, you will see there is a Login option, then a user and password

I tried following the instructions at https://dax.readthedocs.io/en/latest/installing_dax_in_a_virtual_environment.html

```
machine 3tfmri-xnat.bcchr.ca
login <myuser>
password <mypassword>
```

and

`export XNAT_HOST=https://3tfmri-xnat.bcchr.ca`

When I run `XnatCheckLogin`

I get:

```
================================================================
Checking your settings for XNAT
No host specified, using XNAT_HOST environment variable.
Checking login for host=https://3tfmri-xnat.bcchr.ca
Checking connection:host=https://3tfmri-xnat.bcchr.ca, user=<myuser>
 --> error: Wrong login.
================================================================
```

I'm wondering if I also need to include a 'login' in my .netrc file? or set user as BCCHR/<myuser>? OR SOMETHING like that...

I can login to my XNAT on my browser with my user and pwd no problem...

Any insight would help

Cheers,

Alex W.

**Comment by baxpr** [comment]
First guess, do you need

export XNAT_HOST=https://3tfmri-xnat.bcchr.ca/xnat

?

**Comment by weberam2** [comment]
Hi,
Thanks for your fast response

ok, so I added `/xnat` to my XNAT_HOST but still get an error

```
================================================================
Checking your settings for XNAT
No host specified, using XNAT_HOST environment variable.
Checking login for host=https://3tfmri-xnat.bcchr.ca/xnat
Checking connection:host=https://3tfmri-xnat.bcchr.ca/xnat, user=aweber
 --> error: Wrong login.
================================================================
```

**Comment by KarthikMasi** [comment]
I wasn't able to open the URL https://3tfmri-xnat.bcchr.ca on our end. Is the URL network restricted?

Thanks,
Karthik
________________________________

**Comment by weberam2** [comment]
Sorry, I should have mentioned that
Yes, it requires a VPN
However, the computer I am trying to use dax on is on that VPN

Cheers

**Comment by baxpr** [comment]
Is your login an institutional one, handled via LDAP? Or an xnat-specific one (localdb)? I am not sure how pyxnat.Interface works with LDAP credentials.

You might try deleting the .netrc and just entering username/password manually to XnatCheckLogin, if you haven't already.

**Comment by weberam2** [comment]
When i get rid of my ~/.netrc file, I just get this

> XnatCheckLogin

```
================================================================
Checking your settings for XNAT
No host specified, using XNAT_HOST environment variable.
Checking login for host=https://3tfmri-xnat.bcchr.ca/xnat
ERROR:login not found, set in ~/.netrc

```

**Comment by baxpr** [comment]
Closing, because we @VUIIS/vuiis-cci-team are not planning related changes to the codebase. Always open to suggestions though if I've missed anything in the discussion above.
