### ISSUE TITLE
Dax Logo Contest

### ISSUE THREAD

**Issue by byvernault** [VUIIS/dax#41]
Hi guys,

I was thinking about doing a logo for the package since we start using it in different sites and I did several presentation here on it.

I created a simple logo so far. We can do a contest and then choose the best logo. You can improve the one I am posting if you want. :)

Cheers,

Ben
![logo1_dax](https://cloud.githubusercontent.com/assets/3945463/12893166/8ea0d9e6-ce87-11e5-8552-3df1cae0bed6.png)

**Comment by damonms** [comment]
Is the XNAT logo copyrighted? I doubt we're allowed to change it like this.

**Comment by byvernault** [comment]
Good Question :D

**Comment by damonms** [comment]
For consideration. I really like the X. Hopefully we can get approval.
[dax.pdf](https://github.com/VUIIS/dax/files/123466/dax.pdf)

**Comment by byvernault** [comment]
I like it. 

Rick gave me the go to use the X like that from XNAT.

We should add it to your logo and edit the color to keep the same pattern??

**Comment by damonms** [comment]
Let's see if we can get a svg of the logo with layers to more easily manipulate?
________________________________________

**Comment by byvernault** [comment]
Use Matlab do to the logo or even better python :D

**Comment by damonms** [comment]
Nah.
________________________________________

**Comment by damonms** [comment]
![dax](https://cloud.githubusercontent.com/assets/6991533/12930904/892256a2-cf40-11e5-9cd9-d1bdb82bcf85.png)

**Comment by damonms** [comment]
The more I look at this, the more overly-complicated it looks to me

**Comment by michaelpridmore** [comment]
I think the font would look more organized if the X were the same size as the D and the A. This is probably just my OCD talking.

**Comment by byvernault** [comment]
I agree, we need to have them at the same height. But it's a beginning. Thx Steve.

Ben

**Comment by damonms** [comment]
![dax_spider](https://cloud.githubusercontent.com/assets/6991533/12961302/48b2b830-d005-11e5-903a-1bc9635c4777.png)

Because I'm waiting for some code to run

**Comment by bud42** [comment]
I was really digging the other one. I like how each letter symbolizes the word in the acronym.

**Comment by byvernault** [comment]
I prefer the other one. I think if we can paint it in the same color, it will be nice as well.

**Comment by byvernault** [comment]
So what about like that
![dax_logo](https://cloud.githubusercontent.com/assets/3945463/13668132/98bb1c8c-e6b2-11e5-8fc5-d184a4e773fe.png)

**Comment by BennettLandman** [comment]
Nice.

**Comment by damonms** [comment]
Here's a png. If anyone wants to mess around with colors or gradie
![dax_colored](https://cloud.githubusercontent.com/assets/6991533/13675765/be1e9fb2-e6a8-11e5-9381-e198d18a0e71.png)
nts, ill post the eps

**Comment by byvernault** [comment]
Great, let's use this one :)

If everyone approves, we can add it to the github page and to the doc.

**Comment by bud42** [comment]
+1

**Comment by michaelpridmore** [comment]
Very nice! I like the matching color scheme for the different letters

**Comment by byvernault** [comment]
Closing this issue since we have our logo. 

Cheers,

Ben
