### ISSUE TITLE
is_assessor_same_scan_unusable is broken for session processors

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#48]
is_assessor_same_scan_unusable will return 0 for session processors because it always includes scan id. Thus the session processor is never found.

We should add a flag for is_session_processsor=False as the default in the method so no one sees a change.

**Comment by byvernault** [comment]
hmm ... I am trying to remember in which case I am using this method.

I think this is used in the case of scan spiders only. It was created to help the user check that the assessor with a prototype and the a scan is unusable or not. E.G: bedpost checking for dtiQA (same scan) if I remember. It shouldn't be used for checking a session_processor status. 

I am not sure I see in which case you want to use this for a session processor.

**Comment by damonms** [comment]
Bedpost with DTIQA multi.
________________________________________

**Comment by byvernault** [comment]
In that case, It's not on the same scan since it's an assessor on the session. 
I would see the processor run() like :

If assessor_dtiqa_multi.exists() and XnatUtils.is_assessor_usable(assessor_dtiqa_multi):
     return ...
elif XnatUtils.is_assessor_same_scan_unusable(cscan, proctype):
     return ...

I see what you want to do and I agree we should add that by either creating a new function (we don't have to) or just rename the function and add you're idea of the flag and probably call the function :
is_assessor_on_same_session_unusable(cscan, proctype) 

The function will work in both case. Maybe something that is then more generic. 
What do you think?

Cheers,

Ben

**Comment by byvernault** [comment]
Hey Steve,

What do you think about something like this:

def is_assessor_on_same_session_unusable(cobj, proctype, is_scan_proc=False):
    """
    Check to see if the assessor matching the user passed scan and proctype has
     passed QC.
    :param cob: CachedImage object from XnatUtils (scan/session)
    :param proctype: Process type of the assessor to check
    :param is_scan_proc: if the processor is a scan level processor
    :return: 0 if the assessor is not ready or doesn't exist. -1 if it failed,
     or 1 if OK
    """
    obj_info = cobj.info()
    assr_list = list()
    if isinstance(cobj, 'CachedImageScan'):
        if is_scan_proc:
            assr_label = '-x-'.join([obj_info['project_id'], obj_info['subject_label'], obj_info['session_label'], obj_info['ID'], proctype])
        else:
            assr_label = '-x-'.join([obj_info['project_id'], obj_info['subject_label'], obj_info['session_label'],  proctype])
            assr_list = [cassr.info() for cassr in cobj.parent().assessors() if cassr.info()['label'] == assr_label]
    elif isinstance(cobj, 'CachedImageSession'):
        assr_list = [cassr.info() for cassr in cobj.assessors() if cassr.info()['proctype'] == proctype]

    if not assr_list:
        return 0
    elif len(assr_list) == 1:
        return is_bad_qa(assr_list[0]['qcstatus'])
    else:
        # too many assessors checked if one rdy??
        good_assr_list = [assr_info['label'] for assr_info in assr_list if is_bad_qa(assr_info['qcstatus']) == 1]
        if len(good_assr_list) == 1:
            return 1
        elif len(good_assr_list) > 1:
            print "WARNING: too many assessors %s with a good QC status." % (proctype)
            return 0
    return 0

The one thing I am not sure yet is that if there is more than one assessor in the list found with the proctype (e.g: two dtiQA on a session for a session assessor that is checking on dtiQA). Maybe check if only one is good if not let the user know.

Let me know what you think,

Cheers,

Ben

**Comment by damonms** [comment]
I like it. I was also thinking about the case of multiple assessors. Two thoughts here: 1) Returns the list and make the user filter further. 2) Or give an optional list of scan types? This could also still have the case of multiple hits for certain projects with multiple fMRI runs of the same type.

**Comment by byvernault** [comment]
hmmm, we could also separate this function in two:

1) one to return the list of cassr from a cobj (scan or session) where we give the proctype we want to search for.
2) change the code to get the assr_list in the previous method.

Something like:

    def get_cassr_on_same_session(cobj, proctype, is_scan_proc=False):
        """
        Get the list of all assessors with the proctype given for a cobj (session, scan)

        :param cobj: CachedImage object from XnatUtils (scan/session)
        :param proctype: Process type of the assessor to check
        :param is_scan_proc: if the processor is a scan level processor
        :return: list of CachedImageAssessor objects
        """
        obj_info = cobj.info()
        cassr_list = list()
        if isinstance(cobj, 'CachedImageScan'):
            if is_scan_proc:
                assr_label = '-x-'.join([obj_info['project_id'], obj_info['subject_label'], obj_info['session_label'], obj_info['ID'], proctype])
            else:
                assr_label = '-x-'.join([obj_info['project_id'], obj_info['subject_label'], obj_info['session_label'],  proctype])
            cassr_list = [cassr for cassr in cobj.parent().assessors() if cassr.info()['label'] == assr_label]
        elif isinstance(cobj, 'CachedImageSession'):
            cassr_list = [cassr for cassr in cobj.assessors() if cassr.info()['proctype'] == proctype]
        return cassr_list

    def is_assessor_on_same_session_usable(cobj, proctype, is_scan_proc=False):
        """
        Check to see if the assessor matching the user passed scan and proctype has
         passed QC.

        :param cobj: CachedImage object from XnatUtils (scan/session)
        :param proctype: Process type of the assessor to check
        :param is_scan_proc: if the processor is a scan level processor
        :return: 0 if the assessor is not ready or doesn't exist. -1 if it failed,
         or 1 if OK
        """
        cassr_list = get_cassr_on_same_session(cobj, proctype, is_scan_proc)

        if not cassr_list:
            return 0
        elif len(cassr_list) == 1:
            return is_bad_qa(cassr_list[0].info()['qcstatus'])
        else:
            # too many assessors checked if one rdy??
            good_cassr_list = [cassr.info() for cassr in cassr_list if is_bad_qa(cassr.info()['qcstatus']) == 1]
            if len(good_cassr_list) == 1:
                return 1
            elif len(good_cassr_list) > 1:
                print "WARNING: too many assessors %s with a good QC status." % (proctype)
                return 0
        return 0

**Comment by damonms** [comment]
I like it!
________________________________________

**Comment by byvernault** [comment]
Ok doing a push request for that.

**Comment by damonms** [comment]
Done
