### ISSUE TITLE
Logging level configurable via dax_settings (or something else?)

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#62]
Two things I'm getting at here.

1: Could we start to incorporate the logger level in the project settings file. This way we could control logging on a project-by-project basis to expedite debugging.

2: Could we configure the logging via some sort of config file  (outside of dax_settings) so that we can change globally on the fly? This way we don't have to reinstall and we can get depper (or less) logging quickly

**Comment by byvernault** [comment]
I like the idea.

**Comment by damonms** [comment]
I've got something like this working with a WIP "psycoxnat" API. It's a very heavily stripped down pyxnat to ONLY generate the database entries. I'm not going after uploading downloading etc. I don't want to expose a connection to the archive. This, so far, works really nicely in the dev XNAT and i'm following the pyxnat model so we can drop in place with our existing infrastructure for huge projects
