### ISSUE TITLE
xvfb-run with PIDPID

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#64]
We found an interesting issue with using the current SCREEN=$$$$ in the run_spider and template files. On our SGE grid we were getting very high PIDs. These resulted in a PID of > 10 digits. These silently error out in xvfb-run. The proposed solution (that has been working for several days) is to do this

SCREEN=$$$$
SCREEN=${SCREEN:0:8}

(Thanks Andrew for helping out with this).

Are there any objections to a direct commit to master for this since it currently has the possibility to torch silently?

Steve

**Comment by byvernault** [comment]
No problem.

**Comment by damonms** [comment]
Done
