### ISSUE TITLE
check old lock files

### ISSUE THREAD

**Issue by bud42** [VUIIS/dax#66]
we should check for really old lock files and notify the user to consider deleting them.

**Comment by byvernault** [comment]
Yes, I agree. 

I will look into that later this week.

**Comment by damonms** [comment]
I have a crontab set up that deletes flag files over than two days. Are there still issues?

@daily find /scratch/masispider/Spider_Upload_Dir/FlagFiles/* -mtime +2 -delete >> /dev/null

**Comment by damonms** [comment]
Can we make them a bit more intelligent? Maybe store the PID and the parent PID from dax_manager? And then have a daemon that runs in the background removing as needed?
