### ISSUE TITLE
Reproc and "Bad (Needs Edits)" show up as a good cassr

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#68]
This is in dax 0.4.0 release. Just wanted to make sure it's actually fixed in the repo. If not. I'm going to apply a patch because it's broken for a project right now.

**Comment by byvernault** [comment]
Hmm, that should be added with the pull request dax_test we added. Let me check.

**Comment by byvernault** [comment]
Ah I miss read the comment. hmm what is this issue again?

**Comment by bud42** [comment]
wat?

**Comment by damonms** [comment]
It's a case sensitive issue. The case of the qcstatus on XNAT in sent to .lower() though the qc status list is not.

In [3]: BAD = ['Failed', 'Bad', 'Poor', 'Do Not Run']

In [4]: qcstatus = 'Bad (Needs Edits)'

In [5]: for qc in BAD:
   ...:     if qc in qcstatus.split(' ')[0].lower():
   ...:         print "BAD QC"
   ...:         

In [6]: 'Bad' in 'bad'
Out[6]: False

**Comment by damonms** [comment]
Throwing .lower() in qc fixes the issue

**Comment by bud42** [comment]
Steve, I'm looking into this. Are you referring to is_bad_qa() in XnatUtils ?

**Comment by bud42** [comment]
Am I looking at this correctly? is_bad_qa returns 1 if the status is good? Seems backwards.
And is there any case where the current implementation will ever return -1?

**Comment by bud42** [comment]
#72

**Comment by damonms** [comment]
Done
