### ISSUE TITLE
Dax_Setup

### ISSUE THREAD

**Issue by stkbailey** [VUIIS/dax#73]
Hey all - I'm trying to follow the Dax install direcitons, but I'm running into an error that dax_setup has not been run. When I try to run it, though, there a number of questions that I don't know answers to, including  some questions about xsitypes and cluster settings. 

I'm just trying to use the freesurfer editing scripts (fsdownload, fsview and fsupload) to edit some recons. Any tips for getting past this step?

http://dax.readthedocs.io/en/latest/dax_installation.html#install-dax

**Comment by rushtongarth** [comment]
I concur the `dax_setup` seems entirely too laborious for common use.

**Comment by byvernault** [comment]
Hi,

I think you can just press "Enter" for all the questions if you don't know the answer. Most of them are to set up dax for your cluster.

We will work on making dax_setup easier for common use, especially if you don't care of using dax on a cluster. 

Thank you for the feedback.

Best Regards,
Ben

**Comment by stkbailey** [comment]
Thanks, Ben. I got through the setup, but it's throwing an error when I try to import XnatUtils:

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/bailesk1/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/dax/__init__.py", line 1, in <module>
>     import bin
>   File "/home/bailesk1/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/dax/bin.py", line 12, in <module>
>     import XnatUtils
>   File "/home/bailesk1/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/dax/XnatUtils.py", line 35, in <module>
>     import task
>   File "/home/bailesk1/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/dax/task.py", line 7, in <module>
>     import cluster
>   File "/home/bailesk1/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/dax/cluster.py", line 20, in <module>
>     JOB_TEMPLATE = DAX_SETTINGS.get_job_template()
>   File "/home/bailesk1/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/dax/dax_settings.py", line 409, in get_job_template
>     return self.read_file_and_return_template(filepath)
>   File "/home/bailesk1/.pythonbrew/pythons/Python-2.7.10/lib/python2.7/site-packages/dax/dax_settings.py", line 506, in read_file_and_return_template
>     raise OSError(2, 'No data in file', filepath)
> OSError: [Errno 2] No data in file: '/home/bailesk1/.xnat_job_template'

Attached is my settings file that was created. Any suggestions on what I should put into the .xnat_job_template file?

[dax_settings.txt](https://github.com/VUIIS/dax/files/271050/dax_settings.txt)

**Comment by damonms** [comment]
FYI - you just posted your password for your email address. I suggest you change ASAP.

**Comment by stkbailey** [comment]
Yep, forgot that was in there. Thanks for the heads up.

**Comment by bud42** [comment]
Sounds like we need to support dax installs that don't need dax_tools, i.e. only use Xnat_tools and/or freesurfer_tools.

**Comment by rushtongarth** [comment]
Perhaps in the existing `dax_setup` an initial branching question could launch you into either `dax_setup_lite` for non dax_tools builds or `dax_setup_full` for builds requiring dax_tools.  Thoughts?

**Comment by byvernault** [comment]
Yes, I am working on asking if the user want to use the default setup for Xnat_tools/Freesurfer_tools.

**Comment by damonms** [comment]
Done

**Comment by stkbailey** [comment]
Great, thanks!
