### ISSUE TITLE
We need to make a release soon

### ISSUE THREAD

**Issue by damonms** [VUIIS/dax#78]
We have a lot of new features. Let's close as much as we can and release?

**Comment by byvernault** [comment]
I agree. Let’s try to finish all the new features and release a new version of dax.

I think we can work on finishing dax_setup_reform / Diskq and Simple spiders.

Simple processors will probably be the next steps but we can wait the next release.

What do you think?

**Comment by damonms** [comment]
That sounds good to me!

________________________________

**Comment by damonms** [comment]
Some of the other stuff is taking a bit of time. What about making a release now and another later?

**Comment by damonms** [comment]
Closing this as we will release today
