### ISSUE TITLE
Trimming "/" for GET request

### ISSUE THREAD

**Issue by michaelbacci** [VUIIS/dax#88]
Hi,
the utility XnatCheckLogin use the XNAT_HOST variable without trimming the slash "/" for the address.

Let's see this example:

```
INFO: Trying to open a connection with XNAT with your login...
 --> error: Wrong login.
 *Try typing them again:
  --> XNAT_HOST: http://127.0.0.1:9090/
  --> XNAT_USER: admin  
  --> XNAT_PASS:
  --> error: Wrong login.
```

A 'nc' session opened to the 9090 door receveid:

```
$ nc -l 9090
GET //data/JSESSION HTTP/1.1
Host: 127.0.0.1:9090
Authorization: Basic YWRtaW46YWRtaW4=
```

So the `GET //` are an error to fix.
Regards

**Comment by byvernault** [comment]
Hi Michael,
If you set the variable to http://127.0.0.1:9090, does it work then?
I think your host is actually 127.0.0.1:9090.

Cheers,
Ben

**Comment by michaelbacci** [comment]
Yep it works if you remove the last "/".
Not a big error, just a stuff that could be nice to fix.

Thanks
